# Site settings
title: UTRA
email: utra@utra.ca
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://utra.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
